version: '3.7'

services:
  backend:
    image: o3as/o3webapp-be
    restart: unless-stopped
    environment:
      - FLASK_RUN_HOST=0.0.0.0
#   build example from the local folder (check the path!)
    build: 
       context: ./o3webapp-be
       dockerfile: docker/Dockerfile
#   build example from the git repository (default branch)
#    build: 
#       context: https://git.scc.kit.edu/synergy.o3as/o3webapp-be.git
#       dockerfile: docker/Dockerfile
    ports:
      - target: 5000
        published: 5000

  frontend:
    image: o3as/o3webapp-fe
    restart: unless-stopped
#   build example from the local folder (check the path!)
    build:
      context: ./o3webapp-fe
      dockerfile: docker/Dockerfile
#   build example from the git repository (default branch)
    build: 
       context: https://git.scc.kit.edu/synergy.o3as/o3webapp-fe.git
       dockerfile: docker/Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER_URL=http://o3web.test.fedcloud.eu:5000
    ports:
      - target: 3000
        published: 80
#   example on how to mount a folder in the container
#    volumes:
#      - ./:/srv/o3webapp-fe/
