config:
  project_repos:
    o3webapp-fe:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3webapp-fe.git'
      branch: test
#environment:
#  JPL_DOCKERPUSH: "o3webapp"
sqa_criteria:
  qc_style:
    repos:
      o3webapp-fe:
        container: o3webapp-fe-testing
        commands: 
        - bash -c "cd /o3webapp-fe-testing/o3webapp-fe && npm install && eslint ./"
  qc_coverage:
    repos:
      o3webapp-fe:
        container: o3webapp-fe-testing
        commands:
        - bash -c "cd /o3webapp-fe-testing/o3webapp-fe && npm test -- --verbose"
  qc_security:
    repos:
      o3webapp-fe:
        container: o3webapp-fe-testing
        commands:
        - bash -c "cd /o3webapp-fe-testing/o3webapp-fe && npm audit"

timeout: 900
