config:
  project_repos:
    o3webapp-fe:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3webapp-fe.git'
      branch: moved_branch
#environment:
#  JPL_DOCKERPUSH: "o3webapp"
sqa_criteria:
  qc_style:
    repos:
      o3webapp-fe:
        container: o3webapp-fe-testing
  qc_coverage:
    repos:
      o3webapp-fe:
        container: o3webapp-fe-testing

timeout: 900
