version: "3.6"

services:
  o3webapp-fe-testing:
    image: "o3as/ci-images:react"
    container_name: "o3webapp-fe-testing"
    hostname: "o3webapp-fe-testing"
    volumes:
     - type: bind
       source: ./o3webapp-fe
       target: /o3webapp-fe-testing

  o3webapp-fe:
     build:
        context: "."
        dockerfile: "./o3webapp-fe/docker/Dockerfile"
     image: "o3as/o3webapp-fe:latest"